version: '3.1'

volumes:
  pg_project_LiderIT:

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=LiderIT
    volumes:
      - pg_project_LiderIT:/var/lib/postgresql/data
    ports:
      - "5432:5432"